default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  url: postgresql://forumdb_kcfc_user:cZzHHt5vgyXYkbiQejlTcNPNSeWJ8lOS@dpg-cijjghlph6euh7k28urg-a.oregon-postgres.render.com/forumdb_kcfc 
  # <<: *default

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

